### PR TITLE
Adding support to LXC (proxmox4)

### PR DESCRIPTION
**Pull request by antoiner77**
Little fix, not the best but it works,

New network configuration with lxc: 

on your vagrant file:

```proxmox.vm_type = :lxc```
&
```box.vm.network :public_network, ip: '10.150.170.237', interface: 'eth0', bridge: 'vmbr0', gw: '10.150.170.1'```

Managing multiple interfaces does not work yet, do not hesitate to propose a fix

Issue: #25

### CODE REVIEW

**Comment by devekko** [comment]
hi everyone

any chance these PR's could be accepted into the mainline? 

would hate to have to for this provider !

**Comment by devekko** [comment]
btw, for proxmox at ovh a mac address is required

I will compile this and try it

**Comment by antoiner77** [comment]
I'm using proxmox from ovh too and it work like a charm without any mac address, btw, no need to compile :)
Regards

**Comment by devekko** [comment]
huh ! thanks for that info

**Comment by devekko** [comment]
before I forget, is this OVH in France? I remember reading something about mac addresses not being needed in France... anyways, will test in BHS in comings days, maybe actually next week

**Comment by devekko** [comment]
sorry, I had to compile the gem for vagrant from the fork

have I missed something?

**Comment by devekko** [comment]
hi again

I built this gem and am trying lxc

am getting connection errors trying for OVH 

this is my Vagrantfile

Vagrant.configure('2') do |config|

    config.vm.provider :proxmox do |proxmox|
        proxmox.endpoint = 'https://159.39.33.153:8006/api2/json'
        proxmox.user_name = 'root@pam'
        proxmox.password = 'hjdfhfjdshfd'
        proxmox.vm_id_range = 900..999
        proxmox.vm_name_prefix = 'vagrant_'
        proxmox.openvz_os_template = '/var/lib/vz/template/cache/ubuntu-14.04-standard_14.04-1_amd64.tar.gz'
        proxmox.vm_type = :lxc
        proxmox.vm_memory = 512
    end

    config.vm.define :box, primary: true do |box|
        box.vm.box = 'dummy'    
        box.vm.network :public_network, ip: '145.4.191.18', interface: 'eth0', bridge: 'vmbr0', gw: '159.39.33.254'
    end

end


I can test connect

curl -k -d "username=root@pam&password=hjdfhfjdshfd"  https://159.39.33.153:8006/api2/json/access/ticket 
{ "data": { 
  "CSRFPreventionToken":"4EEC61E2:lwk7od06fa1+DcPUwBTXCcndyAY",  
  "ticket":"PVE:root@pam:4EEC61E2::rsKoApxDTLYPn6H3NNT6iP2mv...", 
  "username":"root@pam"}
}

**Comment by antoiner77** [comment]
Built this gem ? Just add the plugin and change the file after  (Check https://github.com/telcat/vagrant-proxmox/issues/25) What's your error ?

**Comment by devekko** [comment]
thanks for responding

hi, thanks for responding... I'll try the method above

I actually tried to merge all repos and build a new plugin, vs modifying existing gem/ plugin source
http://niccolox.org/compile-custom-vagrant-plugin-for-proxmox-provider/

my error

 INFO interface: error: Unable to communicate with proxmox server:

VagrantPlugins::Proxmox::ApiError::UnauthorizedError
Unable to communicate with proxmox server:

VagrantPlugins::Proxmox::ApiError::UnauthorizedError
 INFO interface: Machine: error-exit ["VagrantPlugins::Proxmox::Errors::CommunicationError", "Unable to communicate with proxmox server:\n\nVagrantPlugins::Proxmox::ApiError::UnauthorizedError"]

**Comment by devekko** [comment]
I actually got passed this error 400 which was erroneous

there was a .vagrant folder created with failed attempts and so I 

vagrant destroy -f (probably redundant)
rm -fR .vagrant

then vagrant up provider=proxmox works

now to the next error !

**Comment by linuxmail** [comment]
hi,

I've installed via "vagrant plugin install vagrant-proxmox" (0.0.10) and tried also to create a lxc container on a ZPool. It works with qemu and this [patch](https://github.com/telcat/vagrant-proxmox/pull/31).
With LXC I can create containers via web, but not via Vagrant:

```

[...]
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Proxmox::Errors::CommunicationError: Unable to communicate with proxmox server:
Unable to create the virtual machine!
Cause: 400 Bad Request>
ERROR vagrant: Unable to communicate with proxmox server:
Unable to create the virtual machine!
Cause: 400 Bad Request
ERROR vagrant: /home/dfuchs
[...]
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `call'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/machine.rb:185:in `action'
/opt/vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
 INFO interface: error: Unable to communicate with proxmox server:
Unable to create the virtual machine!
Cause: 400 Bad Request
Unable to communicate with proxmox server:
Unable to create the virtual machine!
Cause: 400 Bad Request
```

My Vagrant file:

```
Vagrant.configure('2') do |config|
   config.vm.provider :proxmox do |proxmox|
      proxmox.endpoint = 'https://pmox-01.foobar:8006/api2/json'
      proxmox.user_name = 'zxy@pve'
      proxmox.password = 'xxxxxxxxx'
      proxmox.vm_id_range = 900..999
      proxmox.vm_name_prefix = 'vagrant_'
      proxmox.openvz_os_template = '/var/lib/vz/template/cache/lxc-template.tar.gz'
      proxmox.vm_type = :lxc
      proxmox.vm_memory = 512
   end

   config.vm.define :box, primary: true do |box|
      box.vm.box = 'dummy'
      box.vm.network :public_network, ip: '1.2.4.3', interface: 'eth0', bridge: 'vmbr1', gw: '1.2.4.254'
   end
end
```

On the PVE side, I don't find any logs, what is going wrong ...

any suggestions ?

cu denny

**Pull request merged**
